version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: Install Project
          command: npm install
      - run:
          name: Print the Current Time
          command: date
          deployment:
            staging:
              branch: master
              heroku:
                appname: officefront
  test:
    docker:
      - image: circleci/node:8.9-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - run:
          name: Front End Unit Tests
          command: npm run testFront
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test
      - deployment
