version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Install Project
          command: sudo npm install -g @angular/cli; npm install
      - run:
          name: Front End Unit Tests
          command: npm run test
      - run:
          name: Print the Current Time
          command: date
