version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9-browsers
        environment:
                    CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run:
          name: Install Project
          command: npm install
      - run:
          name: Front End Unit Tests
          command: npm run testFront
      - run:
          name: Print the Current Time
          command: date
  deployment:
    staging:
      branch: master
      heroku:
        appname: officefront
